Backup impl 2
k0rdent/kcm pull request #841
Opened 2024-12-27 18:30 UTC by zerospiel

#814

2025-01-09 18:12 UTC, zerospiel commented
Ok, I've figured out how to mitigate the issue with the `mutationwebhookconfigurations` and the template resources being declined to created: it needs to be done on the client side during the restoration process (we cannot control it) namely patch the deploy adding the `providertemplates` and `servicetemplates` resource to high priority list, so they are being applied before the `k0rdent` deployment (that problem does not affect the `clustertemplates` since they are alphabetically higher than `deployment.apps`)

The patch is as follows:
```
$ kubectl patch deploy -n velero velero \
--type='json' \
--patch='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--restore-resource-priorities=\"customresourcedefinitions,namespaces,storageclasses,volumesnapshotclass.snapshot.storage.k8s.io,volumesnapshotcontents.snapshot.storage.k8s.io,volumesnapshots.snapshot.storage.k8s.io,datauploads.velero.io,persistentvolumes,persistentvolumeclaims,serviceaccounts,secrets,configmaps,limitranges,pods,replicasets.apps,clusterclasses.cluster.x-k8s.io,endpoints,services,providertemplates.hmc.mirantis.com,servicetemplates.hmc.mirantis.com,-,clusterbootstraps.run.tanzu.vmware.com,clusters.cluster.x-k8s.io,clusterresourcesets.addons.cluster.x-k8s.io,apps.kappctrl.k14s.io,packageinstalls.packaging.carvel.dev\""}]'
```

2025-01-10 13:00 UTC, Kshatrix requested changes

2025-01-10 13:00 UTC, Kshatrix commented on internal/controller/management_backup_controller.go
> +	if err := r.config.InstallVeleroCRDs(uncachedCl); err != nil {
we should install velero as part of the hmc chart as a dependency (similar to cert-manager)

2025-01-10 13:00 UTC, Kshatrix commented on internal/controller/backup/schedule.go
> +		veleroSchedule := &velerov1api.Schedule{
I think we need to control execution ourselves (discussed seperately)

2025-01-10 13:00 UTC, Kshatrix commented on internal/controller/management_backup_controller.go
> +		Watches(&hmcv1alpha1.ClusterDeployment{}, handler.EnqueueRequestsFromMapFunc(func(ctx context.Context, _ client.Object) []ctrl.Request {
we won't need all of the watchers in that case

2025-01-14 19:36 UTC, zerospiel commented on internal/controller/backup/schedule.go
> +		veleroSchedule := &velerov1api.Schedule{
i've finally decided to go with the periodic updates since it is very complicated (and actually) unclear how to properly manipulate with a timer from another instance. i hope polling once a minute for a single API call is an okayish tradeoff compared to too complicated code. check it out

2025-01-15 09:59 UTC, eromanova commented on internal/controller/backup/collect.go
> +		selectors[i+1] = selector(clusterapiv1beta1.ClusterNameLabel, cldeploy.Name)
The `i` variable corresponds to the index of `cldeploys.Items` but when you assign `selectors[i]` this value may already be assigned on the previous iteration by `selectors[i+1] = ...`. Is it correct?

2025-01-15 09:59 UTC, eromanova commented on internal/controller/backup/config.go
> +// Config holds required set of parameters of to successfully install Velero stack and manipulate with it.
Looks like a typo
```suggestion
// Config holds required set of parameters to successfully install Velero stack and manipulate with it.
```

2025-01-15 09:59 UTC, eromanova commented on internal/controller/management_backup_controller.go
> +		requestEqualsMgmt := mgmt != nil && req.Name == mgmt.Name && req.Namespace == mgmt.Namespace
`req.Namespace == mgmt.Namespace` 
Management and ManagementBackup objects are cluster-scoped. Do we need this condition?

2025-01-15 09:59 UTC, eromanova commented on internal/controller/management_backup_controller.go
> +		mgmtBackup.Namespace = req.Namespace
Do we need to set namespace on cluster-scoped `ManagementBackup`?

2025-01-15 16:38 UTC, zerospiel commented on api/v1alpha1/indexers.go
> +		if _, err := strconv.ParseBool(o.GetAnnotations()[ScheduleBackupAnnotation]); err == nil {
i've just pushed the value to fill the index

2025-01-15 16:38 UTC, zerospiel commented on internal/controller/backup/collect.go
> +		selectors[i+1] = selector(clusterapiv1beta1.ClusterNameLabel, cldeploy.Name)
right, thanks for noting, fixed!

2025-01-15 16:39 UTC, zerospiel commented on internal/controller/management_backup_controller.go
> +		requestEqualsMgmt := mgmt != nil && req.Name == mgmt.Name && req.Namespace == mgmt.Namespace
for consistency, but yeah it is not required so I dropped it, resolving this and the same comment below

2025-01-15 16:41 UTC, zerospiel commented
@eromanova @Kshatrix I squashed both the commits into the single to ease the CR. Fine-tuned code blocks along with roles and manually tested from scratch, so now it is finally ready for a proper CR

2025-01-16 15:41 UTC, zerospiel commented on templates/provider/kcm/values.yaml
> +      name: velero-server-sa
`helm` does not allow to configure `values` with templates, unfortunately, but I think we could just go with default options which are:
```yaml
rbac:
  create: true
  clusterAdministrator: true
  clusterAdministratorName: cluster-admin
serviceAccount:
  server:
    create: true
```

considering the currently created cluster role has the same admin permissions. Let's stick to this and cover the caveats/howto in the docs

2025-01-16 17:32 UTC, zerospiel commented on internal/controller/backup/reconcile.go
> +	// TODO: NOTE: should we also set the ownership for the scheduled backups? i don't wanna do this to avoid accidental backups removal
i dropped the ownership in favor of a plain watcher, so the question is not valid now

2025-01-16 17:35 UTC, zerospiel commented on templates/provider/kcm/values.yaml
> +      name: velero-server-sa
I have dropped the `rbac` and the `serviceAccount` in favor of defaults (`clusterAdmin` `clusterrole`). This will be covered in the docs

2025-01-17 09:23 UTC, zerospiel commented
Should chart versions be updated because of the change to the provider label values?

2025-01-20 09:40 UTC, Kshatrix requested changes

2025-01-20 09:40 UTC, Kshatrix commented on api/v1alpha1/management_types.go
> +	StorageLocation string `json:"storageLocation,omitempty"`
I'm a bit concerned that it overlaps with the same field in the backup object. let's discuss if we even need backup parameters in the management object at all

2025-01-20 09:40 UTC, Kshatrix commented on cmd/main.go
> +	flag.BoolVar(&enableVelero, "enable-velero", true, "Enable Velero stack for management cluster backups.")
I don't think we need it as part of the controller configuration. Similar approach to cer-manager and flux would be enough I think (enable/disable subchart)

2025-01-20 10:38 UTC, zerospiel commented on cmd/main.go
> +	flag.BoolVar(&enableVelero, "enable-velero", true, "Enable Velero stack for management cluster backups.")
we need, if no chart is installed and without the flag, the controller starts and then fails because of watching a missing resource `velerov1.Backup`

2025-01-20 10:39 UTC, zerospiel commented on api/v1alpha1/management_types.go
> +	StorageLocation string `json:"storageLocation,omitempty"`
let's discuss, at the moment the ctrl sets up and manages the schedule hence no other way to configure "upstream" velero backups rather than via the mgmt object

2025-01-20 15:26 UTC, Kshatrix approved these changes

2025-01-20 15:28 UTC, eromanova approved these changes

2025-01-20 15:29 UTC, merged